### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Cathella** [Cathella/Newsweek#1]

**Comment by ricardo123321** [comment]
don't forget to add <a> to your list elements

**Comment by ricardo123321** [comment]
do please add a margin between the rows to separate them a little

**Comment by Cathella** [comment]
> don't forget to add to your list elements

to add what @ricardo123321?

**Comment by Cathella** [comment]
> do please add a margin between the rows to separate them a little

okay

**Comment by ricardo123321** [comment]
sorry, the border line

**Comment by LoboArkano** [comment]
You can use this page to convert the SVG code to an SVG file https://www.rapidtables.com/web/tools/svg-viewer-editor.html
The center column should be bigger
In the sections where you have text beside to an image consider use flex instead of columns
Add the weather info on the header

**Comment by ricardo123321** [comment]
also the color top border on the versus part and resize the images

**Comment by Cathella** [comment]
> You can use this page to convert the SVG code to an SVG file https://www.rapidtables.com/web/tools/svg-viewer-editor.html
> The center column should be bigger
> In the sections where you have text beside to an image consider use flex instead of columns

Thank you for link @LoboArkano
Yes i see it is bigger but It seems i cant pull it off with bootstrap columns. If I use col-*-6 it will be very big for the middle column

**Comment by LoboArkano** [comment]
For that, you can use max-width

**Comment by ricardo123321** [comment]
or a set width for each of the breaking points so it looks more accurate

**Comment by Cathella** [comment]
> For that, you can use max-width

okay, noted. Thanks
